<?php

namespace Dpp\BuyersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BuyerCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyerCategoryRepository extends EntityRepository
{

}
