dpp_customers_homepage:
    path:     /
    defaults: { _controller: DppCustomersBundle:Customer:list }
    
dpp_customers_list:
    path:     /
    defaults: { _controller: DppCustomersBundle:Customer:list }
  
dpp_customers_add:
    path:      /add
    defaults:  { _controller: DppCustomersBundle:Customer:create}

dpp_customers_update:
    path:      /update/{customerRef}
    defaults:  { _controller: DppCustomersBundle:Customer:update}

dpp_customers_delete:
    path:      /delete/{customerRef}
    defaults:  { _controller: DppCustomersBundle:Customer:delete}
    
