# src/Dpp/CustomersBundle/Resources/config/validation.yml
Dpp\CustomersBundle\Entity\Customer:
    constraints:
        - Callback: [validate]

Dpp\CustomersBundle\Entity\Category:
    constraints:
        - Callback: [validate]
        