<?php

namespace Dpp\UsersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

 public function findAllByDescription()
    {
        $entityManager = $this->getEntityManager();
        $query = $entityManager->createQuery(
                                                'Select u from Dpp\UsersBundle\Entity\User u order by u.lastName , u.firstName'
                                               );
        return $query->getResult();
    }


}
