<?php

namespace Dpp\CustomersBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Dpp\CustomersBundle\Entity\Customer;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getCountForCustomer(Customer $customer)
    {
        $entityManager = $this->getEntityManager();
        $rsm = new ResultSetMapping();
        $rsm->addScalarResult('count(*)', 'count');
        $query = $entityManager->createNativeQuery(
                                                'Select count(*) from dpp_product where customer_id = :customer_id',
                                               $rsm)
                                ->setParameter('customer_id', $customer->getId());
        return $query->getResult();
    }

}